import "@radix-ui/themes/styles.css";
import './theme-config.css'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { Inter } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={inter.variable}
      >
        <Theme accentColor="yellow" radius="large" scaling="110%">
        <Navbar />
        <main className="p-5">{children}</main>
        <ThemePanel />
        </Theme>      
      </body>
    </html>
  );
}
